#!/usr/bin/env python3
"""gen_stub_rom.py — compile the GDB stub and emit a Verilog combinational ROM.

Usage:
    python3 scripts/gen_stub_rom.py [options]

Produces  rtl/stub_rom.v  with the compiled stub code baked into a
case statement that Yosys synthesises as pure combinational logic.

Options:
    --rom-base   ROM byte base address (default: 0x1000)
    --ram-aw     RAM address width      (default: 12 → ROM at 0x1000)
    --rv32e      Build for RV32E       (default: RV32I)
    --cross      Cross-compiler prefix (default: riscv64-unknown-elf-)
    --output     Output Verilog file   (default: rtl/stub_rom.v)
    --keep       Keep intermediate build artefacts
    --binary     Use a pre-built .bin instead of compiling
"""

import argparse, os, struct, subprocess, sys, textwrap, tempfile, shutil

HEADER = """\
/*-----------------------------------------------------------------------------
 * stub_rom.v — Combinational ROM for the GDB stub.
 *
 * AUTO-GENERATED by scripts/gen_stub_rom.py — do not edit by hand.
 *
 * ROM size : {nbytes} bytes ({nwords} words)
 * Built for: {arch}
 *---------------------------------------------------------------------------*/

module stub_rom #(
   parameter AW = {aw}        // word-address width
)(
   input      [AW-1:0]  addr,
   output reg [31:0]     rdata
);

   always @(*) begin
      case (addr)
"""

FOOTER = """\
         default: rdata = 32'h00000013; // NOP
      endcase
   end

endmodule
"""


def repo_root():
    """Return the repository root (parent of scripts/)."""
    return os.path.normpath(os.path.join(os.path.dirname(__file__), '..'))


def prepare_linker_script(tmpdir, rom_base, rom_size, ram_size, io_base,
                          stub_reserve):
    """Substitute placeholders in stub_link.ld.in → tmpdir/stub.ld."""
    ld_in = os.path.join(repo_root(), 'sw', 'stub_link.ld.in')
    if not os.path.isfile(ld_in):
        sys.exit(f'error: {ld_in} not found')

    with open(ld_in) as f:
        txt = f.read()

    stub_data = io_base - stub_reserve

    txt = txt.replace('@RAM_SIZE@',  f'0x{ram_size:08X}')
    txt = txt.replace('@ROM_BASE@',  f'0x{rom_base:08X}')
    txt = txt.replace('@ROM_SIZE@',  f'0x{rom_size:08X}')
    txt = txt.replace('@IO_BASE@',   f'0x{io_base:08X}')
    txt = txt.replace('@STUB_DATA@', f'0x{stub_data:08X}')

    ld_out = os.path.join(tmpdir, 'stub.ld')
    with open(ld_out, 'w') as f:
        f.write(txt)
    return ld_out


def compile_stub(cross, arch, abi, rom_base, rom_size, ram_size,
                 io_base, stub_reserve, rv32e, keep, tmpdir):
    """Compile crt0_stub.S + gdb_stub.c into a flat binary at rom_base."""

    sw = os.path.join(repo_root(), 'sw')
    asm_src  = os.path.join(sw, 'crt0_stub.S')
    c_src    = os.path.join(sw, 'gdb_stub.c')

    for src in (asm_src, c_src):
        if not os.path.isfile(src):
            sys.exit(f'error: {src} not found')

    cc  = f'{cross}gcc'
    ocp = f'{cross}objcopy'
    sz  = f'{cross}size'

    ld_script = prepare_linker_script(tmpdir, rom_base, rom_size, ram_size,
                                      io_base, stub_reserve)

    elf  = os.path.join(tmpdir, 'stub.elf')
    bbin = os.path.join(tmpdir, 'stub.bin')

    # Assemble crt0_stub.S → crt0_stub.o
    asm_obj = os.path.join(tmpdir, 'crt0_stub.o')
    asm_flags = [
        cc, f'-march={arch}', f'-mabi={abi}',
        '-c', '-o', asm_obj,
        asm_src,
    ]
    print(f'  [AS] {os.path.basename(asm_src)} → {os.path.basename(asm_obj)}')
    subprocess.check_call(asm_flags)

    # Compile gdb_stub.c → gdb_stub.o
    c_obj = os.path.join(tmpdir, 'gdb_stub.o')
    c_flags = [
        cc, f'-march={arch}', f'-mabi={abi}',
        '-Os', '-ffreestanding', '-nostdlib', '-fno-builtin',
        '-fno-pic', '-mcmodel=medlow',
        '-fdata-sections', '-ffunction-sections',
        '-DGDB_STUB',
        f'-DIO_BASE=0x{io_base:04X}',
        '-I', sw,
        '-c', '-o', c_obj,
        c_src,
    ]
    if rv32e:
        c_flags.append('-D__riscv_abi_rve=1')
    print(f'  [CC] {os.path.basename(c_src)} → {os.path.basename(c_obj)}')
    subprocess.check_call(c_flags)

    # Link: crt0_stub.o first (so .isr is at ROM entry), then gdb_stub.o
    link_flags = [
        cc, f'-march={arch}', f'-mabi={abi}',
        '-nostdlib', '-nostartfiles',
        '-Wl,--no-relax', '-Wl,--gc-sections',
        '-T', ld_script,
        '-o', elf,
        asm_obj, c_obj,
    ]
    print(f'  [LD] → {os.path.basename(elf)}')
    subprocess.check_call(link_flags)

    # Extract .isr + .text + .rodata into a flat binary.
    # objcopy extracts from the lowest used address (rom_base).
    ocp_flags = [
        ocp, '-O', 'binary',
        '--only-section=.isr',
        '--only-section=.text',
        '--only-section=.rodata',
        elf, bbin,
    ]
    subprocess.check_call(ocp_flags)

    # Check binary size.
    bin_size = os.path.getsize(bbin)
    if bin_size > rom_size:
        sys.exit(f'error: stub binary ({bin_size} bytes) exceeds ROM size '
                 f'({rom_size} bytes)')

    print(f'  stub binary: {bin_size} bytes '
          f'({bin_size * 100 // rom_size}% of {rom_size} byte ROM)')

    if keep:
        dst = os.path.join(repo_root(), 'build', 'stub')
        os.makedirs(dst, exist_ok=True)
        for f in (elf, bbin, ld_script, asm_obj, c_obj):
            shutil.copy2(f, os.path.join(dst, os.path.basename(f)))
        subprocess.call([sz, elf])

    return bbin


def bin_to_verilog(binpath, rom_base, arch, outpath, rom_size):
    """Read a flat binary and emit Verilog case entries."""

    with open(binpath, 'rb') as f:
        data = f.read()

    # Pad to word boundary
    while len(data) % 4:
        data += b'\x13'  # NOP padding (addi x0,x0,0 = 0x00000013)

    nwords = len(data) // 4
    nbytes = len(data)

    # AW = word-address width for the full ROM region
    rom_words = rom_size // 4
    aw = max((rom_words - 1).bit_length(), 1)

    print(f'  ROM: {nbytes} bytes code, {nwords} words, AW={aw} '
          f'(ROM capacity {rom_words} words)')

    with open(outpath, 'w') as f:
        f.write(HEADER.format(nbytes=nbytes, nwords=nwords, arch=arch, aw=aw))

        for i in range(nwords):
            word = struct.unpack_from('<I', data, i * 4)[0]
            f.write(f"         {aw}'h{i:03X}: rdata = 32'h{word:08X};\n")

        f.write(FOOTER)

    print(f'  wrote {outpath}')


def main():
    ap = argparse.ArgumentParser(description='Generate stub_rom.v')
    ap.add_argument('--rom-base', type=lambda x: int(x, 0), default=None,
                    help='ROM byte base address (default: 2^ram_aw)')
    ap.add_argument('--ram-aw',   type=int, default=12,
                    help='RAM address width (default: 12)')
    ap.add_argument('--rv32e',    action='store_true',
                    help='Build for RV32E (default: RV32I)')
    ap.add_argument('--cross',    default='riscv64-unknown-elf-',
                    help='Cross-compiler prefix')
    ap.add_argument('--output',   default=None,
                    help='Output Verilog file (default: rtl/stub_rom.v)')
    ap.add_argument('--keep',     action='store_true',
                    help='Keep intermediate build artefacts in build/stub/')
    ap.add_argument('--binary',   default=None,
                    help='Pre-built .bin file (skip compilation)')
    ap.add_argument('--stub-reserve', type=int, default=1024,
                    help='Bytes reserved for stub mutable data (default: 1024)')
    args = ap.parse_args()

    # Derived constants
    ram_size  = 1 << args.ram_aw
    rom_base  = args.rom_base if args.rom_base is not None else ram_size
    rom_size  = ram_size            # ROM half = RAM half
    io_base   = ram_size - 16      # last 16 bytes of RAM half = I/O

    arch = 'rv32ec_zicsr' if args.rv32e else 'rv32ic_zicsr'
    abi  = 'ilp32e'       if args.rv32e else 'ilp32'

    output = args.output or os.path.join(repo_root(), 'rtl', 'stub_rom.v')

    print(f'gen_stub_rom: ram_aw={args.ram_aw}  rom_base=0x{rom_base:04X}  '
          f'io_base=0x{io_base:04X}  arch={arch}')

    if args.binary:
        binpath = args.binary
    else:
        tmpdir = tempfile.mkdtemp(prefix='stub_rom_')
        try:
            binpath = compile_stub(args.cross, arch, abi, rom_base, rom_size,
                                   ram_size, io_base, args.stub_reserve,
                                   args.rv32e, args.keep, tmpdir)
        finally:
            if not args.keep:
                shutil.rmtree(tmpdir, ignore_errors=True)

    bin_to_verilog(binpath, rom_base, arch, output, rom_size)


if __name__ == '__main__':
    main()
